# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    build:
        name: ${{ matrix.os }} (py ${{ matrix.version }}${{ matrix.special }})
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                version: [3.7, 3.8, 3.9, '3.10.0-alpha - 3.10']

        steps:
            -   name: Cancel Previous Runs
                uses: styfle/cancel-workflow-action@0.9.0
                with:
                    access_token: ${{ github.token }}

            -   uses: actions/checkout@v2

            -   name: Set up Python ${{ matrix.version }} on ${{ matrix.os }}
                uses: actions/setup-python@v2
                with:
                    python-version: ${{ matrix.version }}

            -   name: Install dependencies
                run: pip install -e .[test]

            -   name: Python info
                run: |
                    which python
                    python --version

            -   name: Installed packages
                run: pip list

            -   name: Test with pytest
                run: pytest

            -   name: Run codecov
                uses: codecov/codecov-action@v2
                with:
                    file: ./coverage.xml
                    name: codecov-umbrella
